config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :shops do
    resources :reviews, except: :index
  end
  root "shops#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/junre.rb
class Junre < ApplicationRecord
  has_many :shops
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :shop
  belongs_to :user
  enum evaluations: { one: 1, two: 2, three: 3, four: 4, five: 5 }

  validates :evaluation, presence: true
  validates :title, presence: true, length: { maximum: 50 }
  validates :body, presence: true, length: { maximum: 500 }
  validates_uniqueness_of :shop_id, scope: :user_id
end

app/models/shop.rb
class Shop < ApplicationRecord
  belongs_to :junre
  has_many :reviews, dependent: :destroy
  has_many :users, through: :reviews
  has_one_attached :image
  attribute :new_image

  validates :name, presence: true, length: { maximum: 50 }
  validates :adress, presence: true, length: { maximum: 100 }
  validates :opentime, length: { maximum: 50 }
  validates :closetime, length: { maximum: 50 }
  validates :regularholiday, length: { maximum: 50 }
  validates :hp, length: { maximum: 1000 }
  validates :description, presence: true, length: { maximum: 1000 }

  scope :find_newest_shops, -> (p) { page(p).per(4).order(publish_date: :desc) }

  before_save do
    self.image = new_image if new_image
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
        :recoverable, :rememberable, :validatable
  has_one_attached :avatar
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?  
  before_action :set_search

  def set_search
    @q = Shop.ransack(params[:q])
    @shops = @q.result.with_attached_image.find_newest_shops(params[:page])
  end

  protected  
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nick_name, :avatar])
    devise_parameter_sanitizer.permit(:account_update, keys: [:nick_name, :avatar])
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_shop, only: [:show, :new, :edit]
  before_action :set_review, only: [:show, :edit, :update, :destroy]

  def new
    @shop = Shop.find(params[:shop_id])
    @review = Review.new
  end  
  def create
    @review = Review.new(review_params)
    @review.attributes = {
      shop_id: params[:shop_id],
      user_id: current_user.id
    }
    if @review.save
      redirect_to @review.shop, notice: "レビューを登録しました。"
    else
      render :new
    end
  end 
  
  def show
  end
  
  def edit
  end  
  def update
    if @review.update(review_params)
      redirect_to @review.shop, notice: "レビューを更新しました。"
    else
      render :edit
    end
  end

  def destroy
    @review.destroy
    redirect_to @review.shop, notice: "レビューを削除しました。"
  end

  private  
  def review_params
    params.require(:review).permit(:title, :body, :evaluation)
  end  
  def set_shop
    @shop = Shop.find(params[:shop_id])
  end

  def set_review
    @review = Review.find(params[:id])
  end
end

app/controllers/shops_controller.rb
class ShopsController < ApplicationController
  before_action :set_shop, only: [:edit, :update, :destroy]

  def index
    @q = Shop.ransack(params[:q])
    @shops = @q.result.with_attached_image.find_newest_shops(params[:page])
  end

  def new
    @shop = Shop.new
  end  

  def create
    @shop = Shop.new(shop_params)
    if @shop.save
      redirect_to @shop, notice: "お店を登録しました。"
    else
    render :new
    end
  end  

  def show
    @shop = Shop.with_attached_image.includes(reviews: :user).find(params[:id])
  end

  def edit
  end 

  def update
    if @shop.update(shop_params)
      redirect_to @shop, notice: "お店を更新しました。"
    else
      render :edit
    end
  end

  def destroy
    @shop.destroy
    redirect_to shops_path, notice: "お店を削除しました。"
  end

  def index
    @shops = Shop.page(params[:page]).per(4)
  end

  private  
  def shop_params
    params.require(:shop).permit(:name, :adress, :opentime, :closetime, :regularholiday, :description, :hp, :new_image, :junre_id)
  end

  def set_shop
    @shop = Shop.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/shops_helper.rb
module ShopsHelper
  def show_shop_image(shop)
    if shop.image.attached?
      image_tag shop.image.variant(resize: "300x300"), class: "img-thumbnail"
    else
      image_tag "no_image.png", class: "img-thumbnail"
    end
  end
  def show_shop_small_image(shop)
    if shop.image.attached?
      image_tag shop.image.variant(resize: "50x50"), class: "img-thumbnail"
    else
      image_tag "no_image.png", class: "img-thumbnail", width: 50
    end
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Ikenomy</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "shared/header" %>

    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <%= render "shared/flash" %>
        </div>
      </div>
      <div class="row">
        <%= yield %>
      </div>
    </div>
  </body>
</html>

app/views/reviews/_form.html.erb
<%= form_with model: [shop, review], local: true do |form| %>
  <%= render "shared/errors", obj: review %>
  <div class="form-group">
    <%= form.label :evaluation %><br>
    <%= form.select :evaluation, Review.evaluations.values, {}, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= form.label :title %><br>
    <%= form.text_field :title, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= form.label :body %><br>
    <%= form.text_area :body, rows: 10, class: "form-control" %>
  </div>
  <%= form.submit class: "btn btn-primary" %>
  <%= link_to t(".back"), shop, class: "btn btn-secondary" %>
<% end %>

app/views/reviews/_review.html.erb
<div>
  <div>
    <% if review.user.avatar.attached? %>
      <%= image_tag review.user.avatar.variant(resize: "60x60"), class: "img-thumbnail" %>
    <% else %>
      <%= image_tag "no_image.png", class: "img-thumbnail", width: 60 %>
    <% end %>
    <span><%= review.user.nick_name %></span>
  </div>
  <div>
    <div>
      <span class="text-warning"><%= "★" * review.evaluation %></span>
      <b><%= link_to review.title, shop_review_path(review.shop, review) %></b>
    </div>
    <small><%= review.created_at.strftime("%Y年%m月%d日") %></small>
  </div>
  <%= simple_format review.body %>
</div>

app/views/reviews/edit.html.erb
<div class="col-md-8 offset-md-2 mt-3">
  <h2 class="text-center"><%= t '.title' %></h2>
  <div class="mb-3">
    <%= show_shop_small_image @shop %>
    <span><%= @shop.name %></span>
  </div>
  <hr>
  <%= render partial: 'form', locals: { shop: @shop, review: @review } %>
</div>

app/views/reviews/new.html.erb
<div class="col-md-8 offset-md-2 mt-3">
  <h2 class="text-center"><%= t '.title' %></h2>
  <div class="mb-3">
    <%= show_shop_small_image @shop %>
    <span><%= @shop.name %></span>
  </div>
  <hr>
  <%= render partial: 'form', locals: { shop: @shop, review: @review } %>
</div>

app/views/reviews/show.html.erb
<div class="col-md-8 offset-md-2 mt-5">
  <h2 class="text-center"><%= t ".title" %></h2>
  <div>
    <% if @review.user.avatar.attached? %>
      <%= image_tag @review.user.avatar.variant(resize: "60x60"), class: "img-thumbnail" %>
    <% else %>
      <%= image_tag "no_image.png", class: "img-thumbnail", width: 60 %>
    <% end %>
    <span><%= @review.user.nick_name %></span>
  </div>
  <hr>
  <div>
    <div>
      <span class="text-warning"><%= "★" * @review.evaluation %></span>
      <b><%= @review.title %></b>
    </div>
    <small><%= @review.created_at.strftime("%Y年%m月%d日") %></small>
  </div>
  <%= simple_format @review.body %>
  <% if user_signed_in? && current_user.id == @review.user_id %>
    <%= link_to t(".edit"), edit_shop_review_path(@shop, @review), class: "btn btn-info" %>
    <%= button_tag t(".delete"), class: "btn btn-warning", data: { toggle: "modal", target: "#delete-review" } %>
  <% end %>
  <%= link_to t(".back"), @shop, class: "btn btn-secondary" %>
</div>

<div class="modal fade" id="delete-review">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel"><%= t(".modal_title") %></h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <p><%= t(".question_review", review: @review.title) %></p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal"><%= t(".chancel") %></button>
        <%= link_to t(".delete_action"), shop_review_path(@shop, @review), method: :delete, class: "btn btn-danger" %>
      </div>
    </div>
  </div>
</div>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
  <div class="alert alert-danger">
    <p><b><%= obj.errors.count %>件のエラーがあります</b></p>
    <ul>
    <% obj.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_flash.html.erb
<% if flash.notice %>
  <div class="alert alert-success" role="alert">
    <%= flash.notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if flash.alert %>
  <div class="alert alert-danger" role="alert">
    <%= flash.alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-red mb-3">
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggler" aria-controls="navbarTogglerDemo03" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <%= link_to t(".title"), root_path, class: "navbar-brand" %>
  <div class="collapse navbar-collapse" id="navbarToggler">
    <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
      <li class="nav-item">
        <%= link_to t(".home"), root_path, class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to t(".new_shop"), new_shop_path, class: "nav-link" %>
      </li>
        <% if user_signed_in? %>
        <li class="nav-item">
          <%= link_to t(".edit_registration"), edit_user_registration_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to t(".log_out"), destroy_user_session_path, method: :delete, class: "nav-link" %>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to t(".new_registration"), new_user_registration_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to t(".log_in"), new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
    <%= search_form_for @q, class: "form-inline my-2 my-lg-0" do |f| %>
      <%= f.search_field :name_or_description_cont, class: "form-control mr-sm-2" %>
      <%= f.submit t(".search"), class: "btn btn-info my-2 my-sm-0" %>
    <% end %>
  </div>
</nav>

app/views/shops/_form.html.erb
<%= form_with model: shop, local: true do |form| %>
  <%= render "shared/errors", obj: shop %>
  <div class="form-group">
    <%= form.label :name %><br>
    <%= form.text_field :name, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= form.label :new_image %><br>
    <%= form.file_field :new_image, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= form.label :adress %><br>
    <%= form.text_field :adress, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= form.label :opentime %><br>
    <%= form.text_field :opentime, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= form.label :closetime %><br>
    <%= form.text_field :closetime, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= form.label :regularholiday %><br>
    <%= form.text_field :regularholiday, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= form.label :junre_id %>
    <%= form.collection_select :junre_id, Junre.all, :id, :name , { include_blank: t(".include_blank") },  { class: "form-control" } %>
  </div>
  <div class="form-group">
    <%= form.label :description %><br>
    <%= form.text_area :description, rows: 10, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= form.label :hp %><br>
    <%= form.text_field :hp, class: "form-control" %>
  </div>

  <%= form.submit class: "btn btn-primary" %>
<% end %>

app/views/shops/edit.html.erb
<div class="col-md-10 offset-md-1 mt-3">
  <h2 class="text-center"><%= t '.name' %></h2>
  <%= render 'form', shop: @shop %>
</div>

app/views/shops/index.html.erb
<% @shops.each do |shop| %>
  <div class="col-lg-3 col-md-4  col-sm-6 mb-3">
    <%= show_shop_image shop %>
    <h4 class="mt-2"><%= link_to shop.name, shop_path(shop) %></h4>
    <p><%= shop.adress %></p>
    <p><%= shop.description %></p>
  </div>
<% end %>

<div class="col-12">
  <%= paginate @shops %>
</div>

app/views/shops/new.html.erb
<div class="col-md-10 offset-md-1 mt-3">
  <h2 class="text-center"><%= t '.name' %></h2>
  <%= render 'form', shop: @shop %>
</div>

app/views/shops/show.html.erb
<div class="col-md-10 offset-md-1 mt-5">
  <h2><%= @shop.name %></h2>
    <div class="row">
    <div class="col-md-4 mb-4">
      <%= show_shop_image @shop %>
    </div>
    <div class="col-md-8">
      <h2><%= @shop.name %></h2>
      <ul>
        <li><b><%= t ".adress" %>: </b><%= @shop.adress %></li>
        <li><b><%= t ".opentime" %>: </b><%= @shop.opentime&.strftime('%H:%M') %></li>
        <li><b><%= t ".closetime" %>: </b><%= @shop.closetime&.strftime('%H:%M') %></li>
        <li><b><%= t ".regularholiday" %>: </b><%= @shop.regularholiday %></li>
        <li><b><%= t ".hp" %>: </b><%= @shop.hp %></li>
        <li><b><%= t ".junre" %>: </b><%= @shop.junre.try(:name) %></li>
      </ul>
    </div>
  </div>
  <hr>
  <h4><%= t ".description" %></h4>
  <%= simple_format @shop.description %>
  <%= link_to t(".edit"), edit_shop_path(@shop), class: "btn btn-primary" %>
  <%= button_tag t(".delete"), class: "btn btn-warning", data: { toggle: "modal", target: "#delete-shop" } %>
  <% if user_signed_in? %>
    <%= link_to t(".review_new"), new_shop_review_path(@shop), class: "btn btn-info" %>
  <% end %>
  <%= link_to t(".return"), shops_path, class: "btn btn-secondary" %>
  <hr>
  <%= render partial: "reviews/review", collection: @shop.reviews %>
</div>

<div class="modal fade" id="delete-shop">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-name" id="exampleModalLabel"><%= t(".modal_name") %></h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <p><%= t(".question_shop", shop: @shop.name) %></p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal"><%= t(".chancel") %></button>
        <%= link_to t(".delete_action"), shop_path(@shop), method: :delete, class: "btn btn-danger" %>
      </div>
    </div>
  </div>
</div>